#pragma once

#include <fstream>
#include <iostream>
#include <cmath>
#include <vector>
#include <string>
#include <algorithm>
#include <set>
#include <random>
#include <complex>

#include <QMainWindow>
#include <QApplication>
#include <QStyleOptionGraphicsItem>
#include <QLineEdit>
#include <QStyle>
#include <QToolBar>
#include <QPainter>
#include <QPushButton>
#include <QLabel>
#include <QFileDialog>
#include <QFont>
#include <QFontDatabase>
#include <QMdiArea>
#include <QTabBar>
#include <QGraphicsView>
#include <QBrush>
#include <QColor>
#include <QMouseEvent>
#include <QGraphicsItem>
#include <QScrollBar>
#include <QFont>
#include <QInputDialog>
#include <QKeyEvent>
#include <QObject>
#include <QThread>
#include <QMutex>
#include <QWaitCondition>
#include <QGestureEvent>
#include <QCommandLineParser>